#!/bin/sh

#zsh
if [ ! -d ~/.oh-my-zsh ] ; then
	echo "install oh-my-zsh"

	sh -c "$(wget https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"
else
	echo "update oh-my-zsh"

	cd ~/.oh-my-zsh/
	#git reset --hard > /dev/null
	git pull --rebase > /dev/null
fi

#vim
if [ ! -d ~/.vim_runtime ] ; then
	echo "install amix/vimrc"

	git clone https://github.com/amix/vimrc.git ~/.vim_runtime
	sh ~/.vim_runtime/install_awesome_vimrc.sh
else
	echo "update amix vimrc"

	cd ~/.vim_runtime/
	#git reset --hard > /dev/null
	git pull --rebase > /dev/null
fi

#oh-my-config
if [ ! -d /xcfg ] ; then
	echo "install oh-my-config"

	git clone https://github.com/kiddlu/oh-my-config.git /xcfg
	\\cp /xcfg/.* ~/ > /dev/null 2>&1
	\\cp -rf /xcfg/.config/ ~/ > /dev/null 2>&1
else
	echo "update oh-my-config"

	cd /xcfg
	git status | grep "nothing to commit" > /dev/null
	if [ $? != 0 ] ; then
		git stash > /dev/null
		git pull --rebase > /dev/null
		git stash pop > /dev/null
	else
		git pull --rebase > /dev/null
	fi
fi

#hello cygwin
if [ ! -d /xbin ] ; then
	echo "install hello-cygwin"
	
	git clone https://github.com/kiddlu/hello-cygwin.git /xbin
	chmod +x /xbin/* 1> /dev/null 2> /dev/null
else
	echo "update hello-cygwin"

	cd /xbin
	git status | grep "nothing to commit" > /dev/null
	if [ $? != 0 ] ; then
		git stash > /dev/null
		git pull --rebase > /dev/null
		git stash pop > /dev/null
	else
		git pull --rebase > /dev/null
	fi
fi
