#!/bin/sh

show_useage()
{
	echo "Windows Android Debug Bridge for Cygwin"
	echo ""
	echo "useage:"
	echo "    wadb flash <partition> <file>  - write a file to a flash partition"
	echo "    wadb push  <local> <remote>    - copy file/dir to device"
	echo "    wadb pull  <remote> <local>    - copy file/dir from device"
	echo "    wadb install <file>            - push file to the device and install it"
	echo "    wadb shell                     - run remote shell interactively"
	echo ""
	echo "    all other useage is same as adb and fastboot"
	echo "    \"adb help\" or \"fastboot help\" to show message"
}

#DEBUG=true
DEVICE_MODE=none

export ADB_TRACE=0

if [ $# == 0 ] ; then
	show_useage
	exit 1
fi

adb devices -l | grep "product" > /dev/null
if [ $? == 0 ] ; then
	DEVICE_MODE=adb
else
	fastboot devices | grep "fastboot" > /dev/null
	if [ $? == 0 ] ; then
		DEVICE_MODE=fastboot
	fi
fi

if [ "$DEBUG" == "true" ] ; then
	echo "DEVICE_MODE is $DEVICE_MODE"
fi

if [ "$DEVICE_MODE" == "adb" ] ; then

	if [ "$1" == "push" ] ; then
		if [ $# != 3 ] ; then
			show_useage
			exit 1
		fi

		WINDOWS_PATH=`cygpath -w $2`

		if [ "$DEBUG" == "true" ] ; then
			echo "command:"
			echo "    adb push $WINDOWS_PATH $3"
		fi

		adb push $WINDOWS_PATH $3
		exit 0
	fi

	if [ "$1" == "pull" ] ; then
		if [ $# != 3 ] ; then
			show_useage
			exit 1
		fi

		WINDOWS_PATH=`cygpath -w $3`\\.

		if [ "$DEBUG" == "true" ] ; then
			echo "command:"
			echo "    adb pull $2 $WINDOWS_PATH"
		fi

		adb pull -a $2 $WINDOWS_PATH
		exit 0
	fi

	if [ "$1" == "install" ] ; then
		if [ $# != 2 ] ; then
			show_useage
			exit 1
		fi

		WINDOWS_PATH=`cygpath -w $2`

		if [ "$DEBUG" == "true" ] ; then
			echo "command:"
			echo "    adb install $WINDOWS_PATH"
		fi

		adb install $WINDOWS_PATH
		exit 0
	fi

	if [ "$1" == "shell" ] ; then
		if [ $# == 1 ] ; then
				if [ "$DEBUG" == "true" ] ; then
					echo "command:"
					echo "    adbputty"
				fi
			adbputty
			exit 0
		fi
	fi

	until [ -z $1 ] ; do
		ADB_PARAM=`echo $ADB_PARAM $1`
		shift
	done

	if [ "$DEBUG" == "true" ] ; then
		echo "command:"
		echo "    adb $ADB_PARAM"
	fi

	adb $ADB_PARAM;
elif [ "$DEVICE_MODE" == "fastboot" ] ; then

	if [ "$1" == "flash" ] ; then
		if [ $# != 3 ] ; then
			show_useage
			exit 1
		fi
		
		WINDOWS_PATH=`cygpath -w $3`

		if [ "$DEBUG" == "true" ] ; then
			echo "command:"
			echo "    fastboot flash $2 $WINDOWS_PATH"
		fi

		fastboot flash $2 $WINDOWS_PATH
		exit 0
	fi

	until [ -z $1 ] ; do
		FASTBOOT_PARAM=`echo $FASTBOOT_PARAM $1`
		shift
	done

	if [ "$DEBUG" == "true" ] ; then
		echo "command:"
		echo "    fastboot $FASTBOOT_PARAM"
	fi
	fastboot $FASTBOOT_PARAM;
else
	echo "wadb error: device not found"
fi