#!/bin/sh

CURRENT_DIR=`pwd`
SERVER_IP=`echo $SSH_CONNECTION | awk '{print $1}'`
CLIENT_IP=`echo $SSH_CONNECTION | awk '{print $3}'`

echo klinec $SERVER_IP "$CURRENT_DIR $CLIENT_IP"
klinec $SERVER_IP "$CURRENT_DIR $CLIENT_IP"

