#!/bin/sh

CURRENT_DIR=`pwd`
SERVER_IP=`echo $SSH_CONNECTION | awk '{print $1}'`
CLIENT_IP=`echo $SSH_CONNECTION | awk '{print $3}'`
NCB_PORT=8963

echo [JUMP] $SERVER_IP "$CURRENT_DIR $CLIENT_IP" | nc $SERVER_IP $NCB_PORT
